### ISSUE TITLE
LSL fails to execute in Windows 10 platform

### ISSUE THREAD

**Issue by TamojitSaha** [gabrielibagon/OpenBCI_LSL#15]
Hello,
I was trying to use python LSL but miserably failed.
I installed all the module individually and as given, after running `python openbci_lsl.py --stream`,
I get the following error:

```
D:\Github\OpenBCI_LSL>python openbci_lsl.py --stream
Traceback (most recent call last):
  File "openbci_lsl.py", line 25, in <module>
    import lib.streamerlsl as streamerlsl
  File "D:\Github\OpenBCI_LSL\lib\streamerlsl.py", line 21, in <module>
    from pylsl import StreamInfo, StreamOutlet
  File "C:\Program Files\Python37\lib\site-packages\pylsl\__init__.py", line 2, in <module>
    from .pylsl import IRREGULAR_RATE, DEDUCED_TIMESTAMP, FOREVER, cf_float32,\
  File "C:\Program Files\Python37\lib\site-packages\pylsl\pylsl.py", line 1200, in <module>
    lib = CDLL(libpath)
  File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
Am I missing something?
Any related help would be appreciated.

**Comment by f2rainforest** [comment]
you can try pylsl version as 1.10.5
