### ISSUE TITLE
Unexpected END_BYTE found <2> instead of <192>

### ISSUE THREAD

**Issue by npdrbong** [gabrielibagon/OpenBCI_LSL#20]
Hi, everyone.

I am new on openbci and try to make it lsl stream for my research.

when I try to start lsl, this error message printed.

Do you have any idea what's going on and how can I fix this?
``
Streaming data...
WARNING:root:ID:<1> <Unexpected END_BYTE found <2> instead of <192>
Warning: ID:<1> <Unexpected END_BYTE found <2> instead of <192>
Exception in thread Thread-1 (start_streaming):
Traceback (most recent call last):
  File "C:\Users\Bong Suhyeon\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Bong Suhyeon\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Bong Suhyeon\Downloads\OpenBCI_LSL-master\OpenBCI_LSL-master\lib\open_bci_v3.py", line 158, in start_streaming
    sample = self._read_serial_binary()
  File "C:\Users\Bong Suhyeon\Downloads\OpenBCI_LSL-master\OpenBCI_LSL-master\lib\open_bci_v3.py", line 225, in _read_serial_binary
    unpacked = struct.unpack('3B', literal_read)
struct.error: unpack requires a buffer of 3 bytes
``

**Comment by devount** [comment]
您好，我已收到您的邮件，我会尽快处理。

**Comment by liilee111** [comment]
So have you solved this problem? I encountered the same warning messages

**Comment by devount** [comment]
您好，我已收到您的邮件，我会尽快处理。
